# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
<<<<<<< HEAD
=======
pesde = "daimond113/pesde@0.5.0-rc.7"
>>>>>>> origin/master
